on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
        
      - name: install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Validate
        run: npm run build validate ${{ github.workspace }}/ /subscriptions/2c4cf3a2-e277-4638-806b-365ba1131c3d/resourceGroups/cicd-rg/providers/Microsoft.DataFactory/factories/adf-test-amit-dev
        working-directory: ${{ github.workspace }}/build

      - name: Validate and Generate ARM template
        run: npm run build export ${{ github.workspace }}/ /subscriptions/2c4cf3a2-e277-4638-806b-365ba1131c3d/resourceGroups/cicd-rg/providers/Microsoft.DataFactory/factories/adf-test-amit-dev "ExportedArmTemplate"
        working-directory: ${{ github.workspace }}/build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/build/ExportedArmTemplate

  release-qa:
    needs: build
    runs-on: ubuntu-latest
    environment: QA   # GitHub environment for secrets + approvals
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: Deploy to QA ADF
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.ADF_NAME }}
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json

  release-prod:
    needs: release-qa
    runs-on: ubuntu-latest
    environment: Prod   # Require manual approval here
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: Deploy to Prod ADF
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.AZURE_RG_PROD }}
          dataFactoryName: ${{ vars.ADF_NAME_PROD }}
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
